name: Release
on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # 安装 Android SDK（必备，否则找不到 build-tools）
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      # 签名 APK
      - name: Sign app APK
        uses: ilharp/sign-android-release@v2
        id: sign_app
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 36.0.0

      # 重命名
      - name: Rename APK
        run: mv ${{ steps.sign_app.outputs.signedFile }} Quizplayer_${GITHUB_REF_NAME}.apk

      # 创建 GitHub Release
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true